language: node_js
node_js:
  - 10
  - 11
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - export PATH="$(yarn global bin):$PATH"
  - yarn global add greenkeeper-lockfile@1
install:
  - yarn global add codecov
before_script:
  - yarn install --production=false
  - greenkeeper-lockfile-update
script:
  - yarn test
  - codecov
after_script:
  - greenkeeper-lockfile-upload
notifications:
  email:
    on_success: never
    on_failure: always
